server:
  port: 8888
eureka:
  client:
    service-url:
#      defaultZone: http://root:booszy@172.17.0.1:8761/eureka
      defaultZone: http://root:booszy@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-config-server
spring:
  application:
    name: springcloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
#        git:
#          uri: https://git.coding.net/yirenyishi/springcloud-config-profile
#          searchPaths: '{application}'
        native:
          search-locations: classpath:/config/**/
security:
  basic:
    enabled: true
  user:
    name: root
    password: booszy